resolver: lts-15.5

extra-deps:
  - moo-1.2
  - gray-code-0.3.1
  - base-noprelude-4.13.0.0
  - random-extras-0.19
  - random-fu-0.2.7.4
  - random-source-0.3.0.8
  - flexible-defaults-0.0.3
  - rvar-0.2.0.4
  - github: nolrai/grenade
    commit: 75f58045719bfa7f8cdb2a6dd85e8a1891d743a5